services:
  - type: web
    name: sadhana-tracker
    env: node
    repo: https://github.com/SwamiAkash108/sadhana-tracker
    plan: free
    buildCommand: npm install --include=dev && (cd server && npm install) && (cd client && npm install --include=dev && npm run build)
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: VAPID_SUBJECT
        value: mailto:akashananda@bhaktimarga.org
      - key: JWT_SECRET
        value: cec46db8bb4172c39642438770211b26d237964f643a5bdb26bacd5227efa3ae
      - key: VAPID_PUBLIC_KEY
        value: BFAE9s_fUaAwixgQpTBbFaIeDGKtV2sOFXghNNngdMBDAEXPC9-zwPuFKkq1_ecitIbRgdtwClQlHbUxLmSz3HU
      - key: VAPID_PRIVATE_KEY
        value: aaX_jFd6Q-_ag4di3yGKxNs-rfUgElKMkfx6zTJqA-I
      - key: TURSO_DATABASE_URL
        value: libsql://sadhana-tracker-swamiakash108.aws-eu-west-1.turso.io
      - key: TURSO_AUTH_TOKEN
        sync: false